version: '3.8'

services:
  web:
    image: nginx:1.23-alpine
    container_name: Koala-prod-web
    working_dir: /application
    volumes:
      - ./environment/dev/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - .:/application
    networks:
      - Koala-prod
    restart: unless-stopped
    depends_on:
      - php
      - database

  php:
    build:
      context: environment/dev/php
      args:
        INSTALL_XDEBUG: ${DOCKER_INSTALL_XDEBUG:-false}
    container_name: Koala-prod-php
    working_dir: /application
    user: ${CURRENT_UID:-1000}
    volumes:
      - .:/application
      - ./environment/dev/php/php.ini:/usr/local/etc/php/conf.d/php.ini
    networks:
      - Koala-dev
    extra_hosts:
      - host.docker.internal:host-gateway
    restart: unless-stopped

  database:
    image: postgres:15
    container_name: Koala-prod-db
    environment:
      - PGPASSWORD=${DOCKER_DB_ROOT_PASSWORD}
      - POSTGRES_DB=${DOCKER_DB_DATABASE}
      - POSTGRES_USER=${DOCKER_DB_USERNAME}
      - POSTGRES_PASSWORD=${DOCKER_DB_PASSWORD}
    ports:
      - ${DOCKER_DB_EXTERNAL_PORT:-5432}:5432
    volumes:
      - Koala-prod-pgsql-data:/var/lib/postgresql/data
    networks:
      - Koala-prod
    restart: unless-stopped

  node:
    image: node:19-alpine3.16
    container_name: Koala-prod-node
    working_dir: /application
    tty: true
    volumes:
      - .:/application
    networks:
      - Koala-prod
    restart: unless-stopped

networks:
  Koala-prod:
    driver: bridge

volumes:
  Koala-prod-pgsql-data:
    name: Koala-prod-pgsql-data
