version: '3'

networks:
  web:
    external: true

services:
  KoalaHR:
    restart: always
    build:
      context: .
      dockerfile: ./docker/production/Dockerfile
    image: Majkuln/KoalaHR:${TAG:-latest}
    volumes:
      - ./.env:/var/www/html/.env
      - ./storage/app:/var/www/html/storage/app
      - ./storage/logs:/var/www/html/storage/logs
    networks:
      - web
    labels:
      - traefik.enable=true
      - traefik.http.routers.KoalaHR.entrypoints=https
      - traefik.http.routers.KoalaHR.rule=Host(`${TRAEFIK_HOST:-koalaHR.inz.stud.dev}`)
      - traefik.http.routers.KoalaHR.service=KoalaHR
      - traefik.http.services.KoalaHR.loadbalancer.server.port=80
      - traefik.http.routers.KoalaHR.tls.certresolver=leresolver
